### ISSUE TITLE
Plotting SI with negative values in {episoap} templates

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#107]
On the current transmissibility template, the SI section includes a function to plot the SI distribution, which currently is restricted to positive values only.
While this is the most common case, there are instances where the SI can also take negative values, such as when there's pre-symptomatic transmission and the IP is longer than the SI (see [visualisation](https://bmjopen.bmj.com/content/bmjopen/11/6/e041240/F1.large.jpg)).
This is the case for the [study that comes up by default](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7324649/figure/fig02/) when using `epiparameter_db` for COVID-19.

Right now this is specified with `si_x <- seq(1L, to = si$prob_dist$qf(0.999), by = 1L)` 

Should I change this to allow negative values as well?

**Comment by Bisaloo** [comment]
Yes, I guess it should then plot from the 0.01 quantile to the 0.999 quantile. How does this sound?

**Comment by CarmenTamayo** [comment]
On the issue I was referring to the section of the template where the SI is plotted, I was wondering if we should plot the entire distribution or keep it as it is to keep only the positive values.
However the same object `si_x` with a vector of values from the distribution is then used in subsequent steps to by EpiNow2 and R0 for the generation time distribution

**Comment by CarmenTamayo** [comment]
To follow up on this issue, the SI distribution (which can have negative values with the normal distribution) is used in the main skeleton of the report for plotting and in the rmd chunks for estimating the generation time.
I suggest that the plot includes all the values of the distribution, from min to max, and that the samples taken from the distribution to estimate GT in the code chunks are restricted to only contain positive values

**Comment by Bisaloo** [comment]
That sounds good to me. We just need to make sure this is very explicitly documented. 

I may also suggest to wait until https://github.com/epiverse-trace/episoap/issues/109#issuecomment-1850168485 is solved before moving forward on this issue.

**Comment by CarmenTamayo** [comment]
@Bisaloo this issue and issue #109 are the only 2 ones left that are kind of blocking merging the PR

**Comment by Bisaloo** [comment]
I see this as a separate issue. Let's address it in a follow up PR.
