### ISSUE TITLE
What to do if parameterised distributions are not on {epiparameter}?

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#114]
At the moment the transmissibility report offers 2 options:

a) A distribution is extracted from the epiparameter database directly and parameters are used for the SI (On PR #100 this is limited to parameterised distributions using "subset = is_parameterised")
b) The user provides the mean and sd of their data and the template includes the conversion to distribution parameters (and since PR #100 an epidist object is created where the conversion happens automatically, as discussed on issue #112 )

There's a potential 3rd option where the distribution obtained from the epiparameter database isn't parameterised- in this case, the template doesn't currently include an option to convert/extract the parameters

For now, we've agreed to assume that a user will either provide the mean and sd of their data and therefore convert them, or that they will want to use the epiparameter database directly, to avoid adding more parameters to the params list (see issue #106 )

This is unless there was a way to automatically convert the summary statistics reported on database studies when extracting them using `epidist_db`, similarly to the `auto_calc_parameters` argument on `epidist` ? If there is a way I haven't managed to do so @joshwlambert

**Comment by joshwlambert** [comment]
All studies in the {epiparameter} database that have summary statistics that can be converted (or extracted) into distribution parameters should be considered "parameterised" and have distribution parameters. This is because the data coming from `epidist_db()` is created using `epidist()`. Please provide a [reprex](https://reprex.tidyverse.org/) to show where this is not the case as it may be a bug.

**Comment by CarmenTamayo** [comment]
So for studies that provide summary statistics, the conversion/extraction is done automatically and included in the database?

**Comment by joshwlambert** [comment]
> So for studies that provide summary statistics, the conversion/extraction is done automatically and included in the database?

Yes.

**Comment by CarmenTamayo** [comment]
> > So for studies that provide summary statistics, the conversion/extraction is done automatically and included in the database?
> 
> Yes.

Okay that's great, so to avoid extracting a study that is not parameterised, because the reported summary statistics weren't enough to do so, but it may be the only study available for a certain disease and parameter type, I've changed the code on the transmissibility template to include `status = is_parameterised` when using `epidist_db`, and studies that aren't won't be used in the templates
