### ISSUE TITLE
what is the difference between `orderly2` and `episoap`?

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/episoap#122]
While sharing the concept of the package with one group of colleagues, they associated it with [{orderly}](https://mrc-ide.github.io/orderly2/index.html), which is not familiar to me. If this package is familiar to developers:

- What features are different between these packages?
- Should this be added in the [related projects](https://epiverse-trace.github.io/episoap/#related-projects) section of the documentation?

**Comment by Bisaloo** [comment]
Thanks for the question!

They are part of the same ecosystem of package but orderly & orderly2 provide the infrastructure to render the reports (handling caching, automatic cache invalidation, etc.) while episoap provides the content, in the form of templates.

There may be space at some point to use orderly under the hood to speed up the rendering of episoap templates (#13) but it's not a priority at the moment. We want to build the content first.
