### ISSUE TITLE
Missing reference `Wallinga2007-hw?` in `.bib`

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/episoap#125]
I noticed there is a missing reference in the report. I am happy to add it to the .bib file if I know the original article.

A google search landed me on this one - is this correct? https://royalsocietypublishing.org/doi/full/10.1098/rspb.2006.3754

If so, I'll go ahead and create a PR to add it. If it's wrong, just let me know what is the original article and I'll add that 😊

**Comment by Bisaloo** [comment]
Yes, this is the correct article :+1:.

The proper fix for this issue may be to remove this paragraph entirely though. We've had numerous conversations about this with @CarmenTamayo and after some hesitation, we agreed it is probably better to only include text for the final readers of the rendered reports, not so much details of what we are doing and how. 
At the moment, we have a mix of moments we are talking to the package user (= the report author), and the report end reader and this is confusing.

To make an analogy with scientific article, we should jump straight to result & discussion of the paper, and skip the methods section.
Everything related to methods should be moved to a separate vignette or converted to comments in R chunks.

**Comment by chartgerink** [comment]
I am happy with whatever route is taken - I enjoyed reading it just now so it would be a shame for this content to be lost. I'll add the reference and then it can still be moved or adjusted at a later time without worry :blush:.
