### ISSUE TITLE
replace `EpiNow2::dist_spec()` with `EpiNow2::pmf()` when appropriate

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/episoap#131]
This is a reminder to suggest that after https://github.com/epiforecasts/EpiNow2/pull/504 gets merged, line 17 could be updated following the chunk below:

https://github.com/epiverse-trace/episoap/blob/8f2d861d52391333e600a09f0a86d04dec230968/inst/rmarkdown/templates/transmissibility/skeleton/rmdchunks/EpiNow2.Rmd#L16-L18

```r
 generation_time <-  generation_time_opts( 
   EpiNow2::pmf(si$prob_dist$d(si_x))
 ) 
```

This came after some exploration shared in #130

**Comment by CarmenTamayo** [comment]
thanks @avallecam for the heads up!
