### ISSUE TITLE
Epicurves description in transmissibility report

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#139]
The report template for transmissibility currently describes that the section "Epidemic curves" generates these curves with or without stratification, however the provided code and resulting epicurves only show stratified epicurves and total no. of cases

@Bisaloo should we also add the total incidence across regions, or remove the "without stratification" bit?
I think we could simply add an overall epicurve/total no. of cases graph to the existing ones

**Comment by Bisaloo** [comment]
> @Bisaloo should we also add the total incidence across regions, or remove the "without stratification" bit?

I don't have a strong preference. Both options sound reasonable and I'm happy to let you decide.

**Comment by CarmenTamayo** [comment]
Hi @Bisaloo , I've noticed that on the [package's vignette](https://epiverse-trace.github.io/episoap/articles/episoap.html) there's indeed an epicurve with overall cases, but this seems to be no longer available on the current template's code- was there a reason for this can you remember? I'll try find the og code

**Comment by CarmenTamayo** [comment]
Fixed in #144

**Comment by Bisaloo** [comment]
Context: this was removed from incidence2 for a while but have been reintroduced in https://github.com/reconverse/incidence2/commit/cda7bf02f08fb85710f9d4d77662fa8c190f7330.
