### ISSUE TITLE
Missing info in EpiNow2 chunk

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#141]
@Bisaloo there's a Rmd code chunk that just says "missing for now" in the EpiNow2 section of the template, should this be removed? the code above it does generate the plot with regional estimates so I'm not sure whether this was a typo or if there's actually some information that needs to be added

https://github.com/epiverse-trace/episoap/blob/2b56ffb61ad8dc68325cff3d1b27c86406a279b7/inst/rmarkdown/templates/transmissibility/skeleton/rmdchunks/EpiNow2.Rmd#L109

**Comment by Bisaloo** [comment]
The idea was to add a boxplot, mustache plot, such as the same one we are provided in the chunk with the same name in the EpiEstim child document:

https://github.com/epiverse-trace/episoap/blob/a44eda57a04a42fc9a23aaaf29491c42e9e18a10/inst/rmarkdown/templates/transmissibility/skeleton/rmdchunks/EpiEstim.Rmd#L148-L165

The overall concept was to have a perfect match (or as good as possible) match across the different package options.

**Comment by CarmenTamayo** [comment]
So should I add this as well? Or was there a blocker for this at the time that I should be aware of? 
Also, I'm not able to knit the template with EpiNow2 because of a lock file error, but at least on the Rmd I see that the chunk starts with an "Explanation" section that appears to be empty- what did you envision to include here? an overview of the package and how it's used to estimate transmissibility? should I add it too? 
https://github.com/epiverse-trace/episoap/blob/a44eda57a04a42fc9a23aaaf29491c42e9e18a10/inst/rmarkdown/templates/transmissibility/skeleton/rmdchunks/EpiNow2.Rmd#L11

**Comment by Bisaloo** [comment]
> So should I add this as well? Or was there a blocker for this at the time that I should be aware of?

As far as I remember, it was mostly a lack of time to do it at the time. It would be great if you can add it.

> chunk starts with an "Explanation" section that appears to be empty- what did you envision to include here?

It was added to match perfectly what is present in the `i2extras` child document. I'm no longer sure what the best solution is here. Maybe this section should be removed from all child documents, including `i2extras`, in line with what we discussed in https://github.com/epiverse-trace/episoap/issues/120.

**Comment by CarmenTamayo** [comment]
Hi @Bisaloo, I'm adding the plots and an explanation for each section so that they're standardised, we/users can judge later whether the explanation is needed or wanted

With EpiNow2 I'm getting this plot which looks a bit odd:
![image](https://github.com/epiverse-trace/episoap/assets/114071268/1d9fc99c-5093-4968-a62e-f3ded8815810)

I've tried using similar input data as in the i2extras one, namely 
- a df containing  Rt estimates over time for each region
- a df with each region's mean, median, 95 lower/upper

I got these data from EpiNow2's output after running regional_epinow, but it's a bit tricky since there are so many to choose from...
This is the code: 

`rt_per_group <- res_epinow2_group$summary$results$estimates$summarised %>%
  dplyr::filter(variable == "R")
res_group_summary <- res_epinow2_group$summary$summarised_results$data %>%
  dplyr::filter(metric == "Effective reproduction no.")`

`rt_per_group %>%
  ggplot(aes(y = .data[[group_var]]), fill = custom_grey) +
  geom_violin(aes(x = mean), fill = pale_green, color = green_grey) +
  geom_pointrange(
    data = res_group_summary,
    aes(x = median, xmin = lower_95, xmax = upper_95),
    color = dark_green
  ) +
  geom_vline(xintercept = 1, color = dark_pink) +
  labs(
    title = "Reproduction numbers",
    subtitle = sprintf(
      "based on data from %s - %s",
      format(min(get_dates(last_counts)), "%d %B %Y"),
      format(max(get_dates(last_counts)), "%d %B %Y")
    ),
    y = "",
    x = "Reproduction number"
  )`

Should I leave it as it is for now or can you spot any mistakes with the input data? thanks!

**Comment by CarmenTamayo** [comment]
This has been addressed in #144  by adding a corresponding section of explanations for the other Rmd chunks (EpiNow2, EpiEstim, R0)
