### ISSUE TITLE
Allowed input file types for {episoap}?

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#146]
Currently the file type is .rds, which was updated from an .xlsx in the previous version of main (before merging #137)- I'd like to add to the explanatory chunk of code which file types are acceptable as an input for {episoap} but I'm not sure if there are others, e.g., .csv, that would also be adequate.

**Comment by Bisaloo** [comment]
Since we use rio, all formats supported by rio are ok: https://gesistsa.github.io/rio/#supported-file-formats

**Comment by CarmenTamayo** [comment]
Thanks Hugo I'll add it
