### ISSUE TITLE
Template still says that {linelist} isn't used?

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#151]
Currently the transmissibility template still says that the linelist package isn't used as there is no integration with other packages

https://github.com/epiverse-trace/episoap/blob/0c525bdeaebc460f7c560dd47f5974434024dd4d/inst/rmarkdown/templates/transmissibility/skeleton/skeleton.Rmd#L295

PR #137 incorporated linelist data as an option for the template- could we remove this line in the text? We need a clean version of the template for version 0.1.0

**Comment by Bisaloo** [comment]
Yes, it's an oversight and it can be removed.

**Comment by CarmenTamayo** [comment]
This is addressed in #144
