### ISSUE TITLE
Bad visibility of plots in R0 chunk

### ISSUE THREAD

**Issue by CarmenTamayo** [epiverse-trace/episoap#152]
Currently the transmissibility by group plot looks very squashed and it's not possible to read the numbers on the y axis or to properly see the curves (see image below)

![image](https://github.com/epiverse-trace/episoap/assets/114071268/00511c34-6d62-4eb1-8b5d-30a55a7fda36)

@Bisaloo do you think this could be fixed in the code in #144  or is it an issue of the overall template?

Thanks!

**Comment by Bisaloo** [comment]
The rmarkdown chunk producing this plot needs to specify a larger `fig.height` value: https://bookdown.org/yihui/rmarkdown-cookbook/figure-size.html

**Comment by CarmenTamayo** [comment]
This has been addressed in #144
