### ISSUE TITLE
externalize code to children

### ISSUE THREAD

**Issue by thibautjombart** [epiverse-trace/episoap#8]
Replace code chunks by small, self-contained external Rmd, included as child documents. This should facilitate code re-use across different documents, and facilitate maintenance, e.g. when ad-hoc code needs replacing by new functionalities.

**Comment by Bisaloo** [comment]
Done in https://github.com/epiverse-trace/episoap/commit/255624e7782cdcdf3ad6684ca43eccc49c6b1ca4.
