### ISSUE TITLE
Use a line list as default pipeline data

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/episoap#89]
Currently the {episoap} transmissibility pipeline uses pre-aggregated COVID data. However, this does not fit with the pipeline's usage of the {linelist} and {incidence2} packages which tag and aggregate line list data. 

Replacing the current default data with a line list would better demonstrate the full functionality of the {episoap} pipeline.

**Comment by pratikunterwegs** [comment]
Taking a look at {linelist} and {incidence2} to understand what they do and what might be required to add them in the pipeline before committing to taking up this issue.

**Comment by joshwlambert** [comment]
Just to clarify, it's not that the packages are not included, but that a line list data set would better demonstrate their functionality.

**Comment by Bisaloo** [comment]
I had a look at the linelist data in global.health and it's too incomplete to make a good example in this pipeline.
